color: fuchsia
fieldLayouts:
  ae381ea2-594d-406b-883a-2d4099e680ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-29T19:01:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 741fd71d-6888-41e2-9711-3304d957e9f2 # Accordion Item
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c426b053-ec9a-40f5-9b57-cc30a91e49db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b704708-3476-4fc6-a031-4f2c309f29ba
        userCondition: null
handle: accordion
hasTitleField: false
icon: feather
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
