allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  4f62e0c9-b001-467b-a47a-aa4d3a7cdf63:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3a85fce-9148-4061-b6c9-eb4bb279823d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a864f587-7735-4034-ae41-263769dc4757 # Heading
            handle: null
            instructions: 'Override the main title'
            label: 'Alternative Title'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f1c8ac5-0100-48e7-b545-4d43ccf83c71
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28e6f572-c5de-4726-85ef-7676117576ff # Excerpt
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce59c291-af34-40e7-b3fe-88a0e5258312
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cc07c179-e1f6-435a-b2e4-0955e3386fc3 # Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d7f48c9-2e48-4435-85cf-44d019d83859
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 377a06eb-170f-436e-9392-81707480533b # Authors
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61d16f88-1952-492e-89b9-8f905cfd7c04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5ed1f012-d78c-4224-a843-56cd4ca55551 # Key Takeaways
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37fa4b60-6471-408d-80f8-59898da246dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab74eae5-e2c1-4646-8cad-ffa2eabc8536 # Post Builder
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc1476ea-74ee-40dc-9d8b-f72bea346a39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 95255bea-a962-460d-b25d-eab23cefc914
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7a3db20e-efb0-4d0f-80b0-10a47de55295 # Sources
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05bce426-d42f-4cea-8dc9-aa013b11de87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 820f7a49-d637-4e14-92b3-783e1f4117e0 # Reviewed Date
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52df53f9-8f45-4cc6-aac9-417a6db2b995
            userCondition: null
            warning: null
            width: 100
        name: Sources
        uid: 9e54241b-e234-4ddd-bac8-f801b6997a50
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bba4f2f2-89bd-46bf-bcd3-c84f2b8ce39c # Related
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6211b9d-fe44-4d75-b8b4-545da6ac8837
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe085027-b931-4d12-a9e5-139c956b178d # Topics
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85ec7ba9-3f5a-4678-9fa4-cc064fd7052c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0bb7fcba-4b6f-4d85-8282-1bcd36190961
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 761cb901-155c-4af8-b4ae-2838334c31c1 # SEO
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd196508-8319-456e-a681-890ea7ca18d0
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2a286689-9e8a-4c04-9a5c-dfd605a7ac15
        userCondition: null
    thumbFieldKey: null
handle: article
hasTitleField: true
icon: newspaper
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
