allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0435ab20-2762-4234-8103-b5ef4317a6b7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3a5b0f3f-dc1e-47c0-a8f3-3099f83496ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 461ea367-abfe-4d42-997d-746526a89771 # Job Title
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6a9bfa6-9656-47bc-8c8b-26f4d55e7d85
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cc07c179-e1f6-435a-b2e4-0955e3386fc3 # Image
            handle: null
            instructions: null
            label: Photo
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb61c617-b3b3-46c4-a9cc-91a852efec09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28e6f572-c5de-4726-85ef-7676117576ff # Excerpt
            handle: null
            instructions: null
            label: 'Short Bio'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d4ac87a-dfbb-4436-9dfa-2ce0e72b591a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 82aff874-1d9c-4829-a5ff-5d128e16698d # Profiles Elsewhere
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa5e2243-2af0-44ef-9e53-69a5de7c65be
            userCondition: null
            warning: null
            width: 100
        name: Profile
        uid: b8d200d5-a275-4f06-b486-ec41acea7852
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab74eae5-e2c1-4646-8cad-ffa2eabc8536 # Post Builder
            handle: null
            instructions: null
            label: 'Longer Bio'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51b49ef0-0be4-4ae9-9b61-847ca8896316
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4ce23d7-664d-4c9d-b313-d69c81e6e1eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 761cb901-155c-4af8-b4ae-2838334c31c1 # SEO
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9d9a8f6-09df-4eb5-8ffa-d65816f28388
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4cd192f4-5df9-4873-ac4c-4b7e192188e7
        userCondition: null
    thumbFieldKey: null
handle: author
hasTitleField: true
icon: user-pen
name: Author
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
