allowLineBreaksInTitles: false
color: indigo
description: null
fieldLayouts:
  4071dbaf-e513-41da-9818-2b81155f442a:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:c88b67d1-9fd3-4343-af95-0f2eb0d21dab'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9fe35334-f235-4cbd-830d-20551ed7f0de # Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d216589c-c6e9-4ac5-a6f4-e6ad3b53d2aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-14T15:53:04+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7ad2db0d-c902-4335-9e3d-624c922e468d
            userCondition: null
          -
            dateAdded: '2025-11-14T15:53:04+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 849a0a73-727d-437d-ad69-882a650bae66
            userCondition: null
        name: Content
        uid: 504144f8-c9c8-4c51-a56c-e994ac6b7670
        userCondition: null
    thumbFieldKey: 'layoutElement:c4adbdaf-1547-4a95-a4d6-8c0edc9756ba'
handle: banner
hasTitleField: false
icon: flag-pennant
name: Banner
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
