allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  6de602b2-573d-4066-9684-198e7360d26d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d64b1ef9-c733-4435-b2ee-8042589dbdbb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cc07c179-e1f6-435a-b2e4-0955e3386fc3 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b705cbe4-2472-408c-8409-2325b812ec38
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28e6f572-c5de-4726-85ef-7676117576ff # Excerpt
            handle: null
            instructions: null
            label: 'Short Description'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4267a5b-6693-408a-9311-5b305d6c010a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d3eba5d7-eac7-41a7-98f5-6c13f73fd73d # ISBN
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e04857fd-5fe8-4cec-a55a-1273eee11efb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 678106cb-b48e-4351-a5db-2c4d8a9cf60c # Author
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 452643d8-4dde-40f1-b4c8-7b53e398a9cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e150044d-b12f-434c-a9f9-d244e2614c38 # Illustrator
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bb3a430-aae6-4085-b8ca-a272cf0310c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 71e40ac8-9d14-4c1b-8a8d-4c7394b44726 # Age Range
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21254e0e-d7f1-49f9-b307-8ba5211c927b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6195ab36-3dd4-4829-9521-4c0113e3438e # Format
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4355605a-8976-41b8-8249-54c838c641f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e489c49d-c32a-4a51-9e1b-5d0e6d78dd8d # Number of Pages
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c86a4131-4a5d-42a4-b15f-1bbe46e131d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a52fc47f-27d0-4193-abac-5d57ce6873f3 # Series Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09ef856f-1086-4fd7-b854-679de4cd4d43
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f19378b7-f590-4de3-a89e-aff501dbdf3b # Series Position
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7a67181-3aa8-4ea5-8799-78a325afdfeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c6b67b6f-24c0-49dc-afa2-cb269487d4b7 # Where to Buy
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e107dfe-041f-459e-81ad-578ea773a998
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 70ac0c99-61b2-431e-be95-bb8c7c932f5d # Genre
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10abf10b-f5e9-4c78-a01d-8d550c81acde
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1f3d229e-5a3b-4dff-85f5-077118c94a63
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 761cb901-155c-4af8-b4ae-2838334c31c1 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0aec48a7-25cf-4800-a12e-8c0221d64aa7
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e993fd43-9564-4496-943f-b248a87048db
        userCondition: null
    thumbFieldKey: null
handle: book
hasTitleField: true
icon: book
name: Book
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
