allowLineBreaksInTitles: false
color: indigo
description: null
fieldLayouts:
  660bf633-c80a-4056-b483-d05c82964461:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-29T19:00:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: edfb9ae5-f698-432c-b828-002685d324fb # Background
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c17ae8b3-c2bc-43a5-a91c-3ba2a9008c48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-29T19:00:49+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ccfe7304-f036-4d18-abc9-0f375b6e20c4
            userCondition: null
          -
            dateAdded: '2025-05-29T19:00:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c9e6e935-5710-4a87-a442-1351e587d602 # Block Heading
            handle: formHeading
            instructions: null
            label: 'Form Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8073e581-9955-4906-a681-adefe1a6e643
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-07-20T06:29:56+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ac25338d-ce3e-46af-ae59-c2a5677f859f
            userCondition: null
          -
            dateAdded: '2026-07-19T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1d4d3a5e-dcf4-4545-9b43-d3bbf747f1f6 # Layout Forms
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 408fa949-7324-4438-98f2-f07b40c2f10c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4647575f-13f6-48f9-a7b8-64bbd86ea22b
        userCondition: null
    thumbFieldKey: null
handle: form
hasTitleField: false
icon: address-card
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
