allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f08e2fed-c9e1-4394-b594-1c4d42f6a32d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: abd58beb-522e-42de-8a56-ef3cf2191204 # Layout Gallery
            handle: null
            instructions: null
            label: Layout
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0223f28c-9079-4fd9-89e9-ace9a423f0d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: da92529b-4111-42fa-bc41-d3773a64c096 # Ticker Direction
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00fb7d1-1d80-4235-938c-299c7a7f1c30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9c150edf-970c-4334-9c04-b4a62138fc45 # Gallery
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76bb5420-8866-496c-98db-10c6585b8ce4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5934883c-9e97-41f1-8ab8-00063ef3dfe3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2c71aa3d-133a-4b8c-9db4-94f0afaf981d # Bookmark
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2963b26c-8124-4087-8de5-5c91b73ed1b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ce1f332d-4ecb-4fe5-81ec-209320969ae2 # Background
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 473a2308-6694-4099-8c2b-7466e6533f86
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5df22e15-45f0-4766-8d0a-4d95df967f40 # Background Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3a697fe-3ff4-4d28-bd4e-e88a65e834aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c9e6e935-5710-4a87-a442-1351e587d602 # Block Heading
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f81336b-1771-43a5-8501-9f3df346f957
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 1ca7b444-bc01-4349-95a6-54e8bc2a3934
        userCondition: null
    thumbFieldKey: null
handle: gallery
hasTitleField: false
icon: images
name: Gallery
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
