allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  fd73c5c1-6b3b-46cb-8b89-9d3d7670ca8d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e009930d-bf03-4623-81f1-45dc3027d4ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a864f587-7735-4034-ae41-263769dc4757 # Heading
            handle: null
            instructions: 'Override the main title'
            label: 'Alternative Title'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 358a668e-defe-4df6-a9e5-83be7398884d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28e6f572-c5de-4726-85ef-7676117576ff # Excerpt
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f524e3-fc70-47d4-a133-483aeeef31db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cc07c179-e1f6-435a-b2e4-0955e3386fc3 # Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47e234a9-8000-4f40-9a44-9c1c8d4fe580
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 72282bfa-e065-4688-ba88-244a24ef48c1 # Client
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dac33cb-ea6c-4d55-b33b-1528e6f18e78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 13ea6cb5-9095-49da-92c2-237d05e15ccb # Project Date
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2ea7756-2d72-481b-9a18-f2dae16a716b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 31d5c9e8-8e6e-47a9-9a15-7b363b2a1e0d # Location
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9779173-c846-454c-996e-d5a78345537f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6fae30f1-fbac-4399-a18d-8e30006f644f # Services
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50b7a84a-9512-4ad4-9e6b-a9144550a27f
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: fbaacc7d-292b-4a80-937d-f3520135ed65
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9c150edf-970c-4334-9c04-b4a62138fc45 # Gallery
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e59c02af-9921-404a-8900-2f0332c181be
            userCondition: null
            warning: null
            width: 100
        name: Gallery
        uid: 9738ba47-a548-4917-bb82-9b7c9cfb6334
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7905031c-3482-4874-ae43-5aed9de263d0 # Page Builder
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0b676f3-c016-420e-8905-a10a396c1ba2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 071178ba-e68f-4fe6-bcbc-c969762ebb95
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bba4f2f2-89bd-46bf-bcd3-c84f2b8ce39c # Related
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d322a57-bec4-4142-9436-e3bd4cd67f64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fe085027-b931-4d12-a9e5-139c956b178d # Topics
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2aaab77-69f3-48f8-b46b-d56de6a94b33
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0179fa22-97d2-4b92-ab0c-bbb1deecfa39
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 761cb901-155c-4af8-b4ae-2838334c31c1 # SEO
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a8c1025-40fb-4d03-bd5c-934e1498d01d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9e0ef31a-0411-4a8f-a37d-ae3c76fc8bde
        userCondition: null
    thumbFieldKey: null
handle: project
hasTitleField: true
icon: briefcase
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
