allowLineBreaksInTitles: false
color: indigo
description: null
fieldLayouts:
  7c7f3c7d-622a-4a80-9fdb-10f1d0c83ebc:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:106dfc18-9249-4280-bad1-32f86660821f'
      - 'layoutElement:3603ec0f-3fe6-4f1b-bc4e-9adad5bfc761'
      - 'layoutElement:c7334be4-f086-4f92-9d41-72ccd294f3cd'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9fe35334-f235-4cbd-830d-20551ed7f0de # Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d0f0fc7-eadf-4f38-b822-56058c27fbe4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T18:31:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d9cb6e21-440e-4ea9-8251-5e34bd332f11
            userCondition: null
          -
            dateAdded: '2025-11-07T18:31:14+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 72af94b8-b430-452c-bb24-1b0dd17dc7bd
            userCondition: null
        name: Content
        uid: f021bc94-6555-42a1-b139-c88c11011100
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-06T22:20:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c9e6e935-5710-4a87-a442-1351e587d602 # Block Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc138d9f-816f-40ff-8b7f-92d3b5fa9e3c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e33c8b6a-a59d-48c9-a211-8c9115b16a7a
        userCondition: null
    thumbFieldKey: 'layoutElement:a5ede03d-d705-4991-963b-34203fce1cab'
handle: spotlight
hasTitleField: false
icon: lightbulb
name: Spotlight
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
