<?php

namespace modules\stablestwigextensions\services;

use Craft;

/**
 * Generates the CP stylesheet that hides fields the current block can't use —
 * an item field the parent block doesn't want, or one of the block's own fields
 * that only applies to some of its layouts.
 *
 * Craft evaluates field conditions against the element being edited and ships
 * no owner-aware rule, so a nested item cannot know which block contains it.
 * CSS can — but where it finds that out depends on the Matrix field's view
 * mode, and both have to be covered:
 *
 *   blocks view    the parent renders inline, so the item's .matrixblock is a
 *                  descendant of the parent's and a plain descendant selector
 *                  works.
 *
 *   cards view     the parent opens in a slideout, and its own .matrixblock is
 *                  NOT in that DOM at all — the form replaces it. The type is
 *                  instead in the slideout's sidebar, as the entry type select's
 *                  numeric value, a sibling of the content. :has() is what
 *                  reaches back up from the fields to check it.
 *
 * That numeric id is why this is generated rather than a static file: type ids
 * are per-database, so a hand-written `[data-value="28"]` would silently mean a
 * different block on every other site. Resolving handles at runtime keeps the
 * rules portable and makes a renamed or deleted block fail loudly here rather
 * than quietly mis-hide a field.
 */
class BlockFieldCss
{
    public function generate(): string
    {
        $config = \modules\support\Config::get('blockfields');
        if (!$config) {
            return '';
        }

        $blocks = $config['blocks'] ?? [];
        $this->assertNoOverlaps($blocks);

        $rules = array_merge(
            $this->hiddenItemFieldRules($blocks),
            $this->perLayoutRules($blocks),
            $this->layoutOptionRules($blocks),
            $this->lockedTypeRules($config['switchGroups'] ?? []),
        );

        if (!$rules) {
            return '';
        }

        return "/* Generated by BlockFieldCss from config/stables/blockfields.php — do not edit. */\n"
            . implode("\n\n", $rules);
    }

    /**
     * A field listed as structurally hidden AND layout-conditional is a
     * contradiction — either a stale leftover from before it was made
     * structural, or a typo that would otherwise defeat the per-layout rule
     * silently. Fail at generation time rather than let one tier quietly win.
     *
     * @param array<string, array> $blocks
     */
    private function assertNoOverlaps(array $blocks): void
    {
        foreach ($blocks as $blockHandle => $blockConfig) {
            $hidden = $blockConfig['itemFields']['hidden'] ?? [];
            if (!$hidden) {
                continue;
            }

            $conditional = [];
            foreach ($blockConfig['itemFields']['perLayout'] ?? [] as $fieldMap) {
                $conditional = array_merge($conditional, array_keys($fieldMap));
            }

            $overlap = array_intersect($hidden, $conditional);
            if ($overlap) {
                throw new \yii\base\InvalidConfigException(sprintf(
                    'blockfields config: %s %s both always-hidden and per-layout for block "%s" — pick one.',
                    implode(', ', $overlap),
                    count($overlap) === 1 ? 'is' : 'are',
                    $blockHandle
                ));
            }
        }
    }

    /**
     * Item fields a block never uses, regardless of layout.
     *
     * @param array<string, array> $blocks
     */
    private function hiddenItemFieldRules(array $blocks): array
    {
        $entries = Craft::$app->getEntries();
        $rules = [];

        foreach ($blocks as $blockHandle => $blockConfig) {
            $hidden = $blockConfig['itemFields']['hidden'] ?? [];
            if (!$hidden) {
                continue;
            }

            $blockType = $entries->getEntryTypeByHandle($blockHandle);
            if (!$blockType) {
                // A block that no longer exists is a stale config line, not a
                // reason to drop every other rule.
                continue;
            }

            $selectors = [];

            foreach ($hidden as $fieldHandle) {
                $field = '[data-attribute="' . $this->escape($fieldHandle) . '"]';

                // Inline (blocks view): parent block wraps the item.
                $selectors[] = sprintf(
                    '.matrixblock[data-type="%s"] .matrixblock[data-type="item"] %s',
                    $this->escape($blockHandle),
                    $field
                );

                // Slideout (cards view): anchor on the block's own field
                // layout tab, as a DIRECT CHILD of .so-content.
                //
                // The child combinator is load-bearing. Bare
                // :has([data-layout-tab=X]) means "this form contains X
                // somewhere", and a cards slideout contains its item blocks —
                // whose tabs sit deeper, inside .matrixblock > .fields. So the
                // rules for `item` were matching every slideout that held one.
                // Only the form's own tab is a direct child of .so-content.
                //
                // Not the sidebar's entry type select, either: its data-value is
                // written once at first render and not rewritten when the
                // selection changes, so the rules stayed on the previous type
                // until the flyout was saved. The tab is part of the fields
                // Craft re-renders with the new type.
                foreach ($this->tabUids($blockType) as $tabUid) {
                    $selectors[] = sprintf(
                        '.cp-screen:has(.so-content > [data-layout-tab="%s"]) %s',
                        $this->escape($tabUid),
                        $field
                    );
                }
            }

            $rules[] = implode(",\n", $selectors) . " {\n    display: none;\n}";
        }

        return $rules;
    }

    /**
     * Fields — the block's own, or its items' — that only apply to some of
     * the block's layouts. Both are the same CSS shape (hide unless the
     * layout radio's live :checked value is one of the allowed ones); the
     * only difference is how deep the target field sits, which is what
     * perLayoutFieldRules()'s $fieldSelector callback captures.
     *
     * @param array<string, array> $blocks
     */
    private function perLayoutRules(array $blocks): array
    {
        $entries = Craft::$app->getEntries();
        $rules = [];

        foreach ($blocks as $blockHandle => $blockConfig) {
            $blockType = $entries->getEntryTypeByHandle($blockHandle);
            if (!$blockType) {
                continue;
            }

            $rules = array_merge(
                $rules,
                $this->perLayoutFieldRules(
                    $blockHandle,
                    $blockType,
                    $blockConfig['ownFields']['perLayout'] ?? [],
                    fn(string $fieldHandle) => '[data-attribute="' . $this->escape($fieldHandle) . '"]',
                ),
                $this->perLayoutFieldRules(
                    $blockHandle,
                    $blockType,
                    $blockConfig['itemFields']['perLayout'] ?? [],
                    fn(string $fieldHandle) => '.matrixblock[data-type="item"] [data-attribute="' . $this->escape($fieldHandle) . '"]',
                ),
            );
        }

        return $rules;
    }

    /**
     * Hides a field on the layouts it doesn't apply to.
     *
     * Not about ownership — a condition wouldn't follow the editor's clicks
     * either way, since field conditions are evaluated server-side against
     * the saved element. The layout selector renders as a radio group
     * (verbb/buttonbox), so `:checked` is the live selection and CSS
     * re-evaluates on every click.
     *
     * Written as "hide unless one of these is checked" rather than
     * hide-then-reveal so the field stays visible if the markup ever moves —
     * a field showing on a layout that ignores it is untidy, one that can
     * never be reached is a bug.
     *
     * @param array<string, array<string, string[]>> $layoutFieldMap layout field handle => field handle => layout values
     * @param callable(string): string $fieldSelector how to reach the target field from the block's own scope
     */
    private function perLayoutFieldRules(
        string $blockHandle,
        \craft\models\EntryType $blockType,
        array $layoutFieldMap,
        callable $fieldSelector
    ): array {
        $rules = [];

        foreach ($layoutFieldMap as $layoutHandle => $fieldMap) {
            foreach ($fieldMap as $fieldHandle => $layoutValues) {
                $layoutValues = $this->knownOptionValues($layoutHandle, (array)$layoutValues);
                if (!$layoutValues) {
                    // No option matched, so no rule can be right — leave
                    // the field alone rather than hide it on every layout.
                    continue;
                }

                $field = $fieldSelector($fieldHandle);
                $checked = sprintf(
                    '[data-attribute="%s"] input:checked:is(%s)',
                    $this->escape($layoutHandle),
                    implode(', ', $this->valueSelectors($layoutValues))
                );

                // Inline (blocks view): the block is its own .matrixblock,
                // holding both the layout radio and the target field.
                $selectors = [sprintf(
                    '.matrixblock[data-type="%s"]:not(:has(%s)) %s',
                    $this->escape($blockHandle),
                    $checked,
                    $field
                )];

                // Slideout (cards view): same identification as
                // hiddenItemFieldRules() — the block's own layout tab as a
                // direct child of .so-content. Every tab is in the DOM
                // whether or not it's the open one, so the layout radio and
                // the target field can sit on different tabs.
                foreach ($this->tabUids($blockType) as $tabUid) {
                    $selectors[] = sprintf(
                        '.cp-screen:has(.so-content > [data-layout-tab="%s"]):not(:has(.so-content %s)) %s',
                        $this->escape($tabUid),
                        $checked,
                        $field
                    );
                }

                $rules[] = implode(",\n", $selectors) . " {\n    display: none;\n}";
            }
        }

        return $rules;
    }

    /**
     * Values a layout picker offers that this site chooses not to — hides
     * that option from the CP picker entirely, rather than leaving it
     * pickable for a layout the site never wired up.
     *
     * Every other rule builder here has to reach across an owner boundary
     * (block vs. item) and cover both blocks-view and cards-view DOM shapes.
     * This doesn't: a layout field's option row (verbb/buttonbox renders each
     * as `<label class="buttonbox-button"><input value="...">`) renders once,
     * identically, wherever `[data-attribute="$layoutHandle"]` itself renders
     * — there's no owner to be relative to, so one selector covers every
     * view mode and every block that happens to use the field.
     *
     * A value already saved on existing content is untouched by hiding it:
     * the entry keeps it, the picker just shows nothing checked until an
     * editor picks a different option.
     *
     * @param array<string, array> $blocks
     */
    private function layoutOptionRules(array $blocks): array
    {
        $entries = Craft::$app->getEntries();
        $rules = [];

        foreach ($blocks as $blockHandle => $blockConfig) {
            $layoutOptions = $blockConfig['layoutOptions'] ?? [];
            if (!$layoutOptions) {
                continue;
            }

            if (!$entries->getEntryTypeByHandle($blockHandle)) {
                // A block that no longer exists is a stale config line, not a
                // reason to drop every other rule.
                continue;
            }

            foreach ($layoutOptions as $layoutHandle => $hiddenValues) {
                $hiddenValues = $this->knownOptionValues($layoutHandle, (array)$hiddenValues);
                if (!$hiddenValues) {
                    continue;
                }

                $rules[] = sprintf(
                    '[data-attribute="%s"] label.buttonbox-button:has(%s) {' . "\n" . '    display: none;' . "\n" . '}',
                    $this->escape($layoutHandle),
                    implode(', ', $this->valueSelectors($hiddenValues))
                );
            }
        }

        return $rules;
    }

    /**
     * Attribute selectors matching an option's rendered input value.
     *
     * Craft base64-encodes option values into the value attribute
     * (BaseOptionsField::encodeValue), so `[value="hero"]` matches nothing —
     * the DOM says `value="base64:aGVybw=="`. Both forms are emitted rather
     * than only the encoded one, so the rules survive a field type that
     * renders its values plainly.
     *
     * @param string[] $values
     * @return string[]
     */
    private function valueSelectors(array $values): array
    {
        $selectors = [];

        foreach ($values as $value) {
            $selectors[] = '[value="' . $this->escape($value) . '"]';
            // base64 is [A-Za-z0-9+/=], all safe inside a quoted selector.
            $selectors[] = '[value="base64:' . base64_encode($value) . '"]';
        }

        return $selectors;
    }

    /**
     * The configured values that the options field actually offers.
     *
     * A value that no longer exists — renamed layout, typo — would otherwise
     * produce a selector that never matches, which for a "hide unless" rule
     * means the field is hidden everywhere.
     *
     * @param string[] $values
     * @return string[]
     */
    private function knownOptionValues(string $fieldHandle, array $values): array
    {
        $field = Craft::$app->getFields()->getFieldByHandle($fieldHandle);
        if (!$field instanceof \craft\fields\BaseOptionsField) {
            return [];
        }

        $known = array_column($field->options, 'value');

        return array_values(array_intersect($values, $known));
    }

    /**
     * Hides the Entry Type field on nested blocks that aren't in a switch
     * group at all.
     *
     * Filtering the dropdown only protects the blocks that have a group.
     * Everything else still offered the full list, and switching any of them
     * erases whatever the new type doesn't have — so for those the control is
     * removed rather than narrowed. If no switch is safe, none should be
     * offered.
     *
     * Scoped to nested block types only, by their own layout tabs. A section's
     * entry editor is untouched, where changing entry type is a normal thing
     * to want.
     *
     * @param array<int, string[]> $groups
     */
    private function lockedTypeRules(array $groups): array
    {
        $grouped = [];
        foreach ($groups as $group) {
            foreach ($group as $handle) {
                $grouped[$handle] = true;
            }
        }

        $entries = Craft::$app->getEntries();
        $selectors = [];

        foreach ($this->nestedTypeHandles() as $handle) {
            if (isset($grouped[$handle])) {
                continue;
            }

            $type = $entries->getEntryTypeByHandle($handle);
            if (!$type) {
                continue;
            }

            foreach ($this->tabUids($type) as $tabUid) {
                $selectors[] = sprintf(
                    '.cp-screen:has(.so-content > [data-layout-tab="%s"]) .so-sidebar [data-attribute="typeId"]',
                    $this->escape($tabUid)
                );
            }
        }

        return $selectors
            ? [implode(",\n", $selectors) . " {\n    display: none;\n}"]
            : [];
    }

    /**
     * Every entry type that only ever exists inside a Matrix field. These are
     * the ones where switching type is a page-builder action rather than an
     * editorial one.
     *
     * @return string[]
     */
    private function nestedTypeHandles(): array
    {
        $handles = [];

        foreach (Craft::$app->getFields()->getAllFields() as $field) {
            if (!$field instanceof \craft\fields\Matrix) {
                continue;
            }

            foreach ($field->getEntryTypes() as $type) {
                $handles[$type->handle] = true;
            }
        }

        return array_keys($handles);
    }

    /**
     * The switch groups as entry type id => allowed ids, for the JS that
     * filters the type dropdown.
     *
     * This is JS rather than CSS because Garnish appends an open disclosure
     * menu to document.body — it isn't a descendant of the form being edited,
     * so no selector can scope it to the current block's type.
     *
     * @return array<int, int[]>
     */
    public function switchGroupMap(): array
    {
        $config = \modules\support\Config::get('blockfields');
        $entries = Craft::$app->getEntries();
        $map = [];

        foreach ($config['switchGroups'] ?? [] as $group) {
            $ids = [];

            foreach ($group as $handle) {
                $type = $entries->getEntryTypeByHandle($handle);
                if ($type) {
                    $ids[] = (string)$type->id;
                }
            }

            // A group of one restricts nothing, and a group of none is a stale
            // config line — neither is worth emitting.
            if (count($ids) < 2) {
                continue;
            }

            foreach ($ids as $id) {
                $map[$id] = $ids;
            }
        }

        return $map;
    }

    /**
     * Every entry type offered alongside this one — i.e. allowed by the same
     * Matrix field. That's the set the type dropdown can actually show.
     *
     * @return array<string, int> handle => id
     */
    private function siblingTypeIds(string $handle): array
    {
        $type = Craft::$app->getEntries()->getEntryTypeByHandle($handle);
        if (!$type) {
            return [];
        }

        $siblings = [];

        foreach (Craft::$app->getFields()->getAllFields() as $field) {
            if (!$field instanceof \craft\fields\Matrix) {
                continue;
            }

            $ids = array_map(fn($t) => $t->id, $field->getEntryTypes());
            if (!in_array($type->id, $ids, true)) {
                continue;
            }

            foreach ($field->getEntryTypes() as $sibling) {
                $siblings[$sibling->handle] = $sibling->id;
            }
        }

        return $siblings;
    }

    /**
     * The field layout tab uids for an entry type. A layout can have several
     * tabs, and any of them being present identifies the type.
     *
     * @return string[]
     */
    private function tabUids(\craft\models\EntryType $entryType): array
    {
        $layout = $entryType->getFieldLayout();

        return $layout ? array_map(fn($tab) => $tab->uid, $layout->getTabs()) : [];
    }

    /** Handles are [a-zA-Z0-9_]+ in Craft, but this is going into a selector. */
    private function escape(string $value): string
    {
        return preg_replace('/[^a-zA-Z0-9_-]/', '', $value);
    }
}
