<?php

/**
 * AUTO-GENERATED by modules/themedesigner's Backgrounds tab — hand edits
 * here get overwritten on the next save. Every theme's background swatch
 * list, keyed by color role (the stable identifier — labels are just
 * display text and can change freely). `enabled` false means explicitly
 * toggled off (kept, not deleted, so it's distinguishable from a role
 * that's simply never been decided one way or the other, which defaults
 * to enabled). Required by config/colour-swatches.php.
 */
return [
    'default' => [
        'primary' => ['label' => 'Primary', 'hex' => '#00aeef', 'class' => 'bg--primary', 'enabled' => true],
        'secondary' => ['label' => 'Secondary', 'hex' => '#ff6b4a', 'class' => 'bg--secondary', 'enabled' => true],
        'tertiary' => ['label' => 'Calm', 'hex' => '#f7ddb2', 'class' => 'bg--tertiary', 'enabled' => true],
        'dark' => ['label' => 'Dark', 'hex' => '#14213d', 'class' => 'bg--dark', 'enabled' => true],
    ],
    'coastal' => [
        'primary' => ['label' => 'Primary', 'hex' => '#0e8f8a', 'class' => 'bg--primary', 'enabled' => true],
        'secondary' => ['label' => 'Secondary', 'hex' => '#143c4d', 'class' => 'bg--secondary', 'enabled' => true],
        'dark' => ['label' => 'Dark', 'hex' => '#000', 'class' => 'bg--dark', 'enabled' => true],
    ],
];
