<?php

/**
 * AUTO-GENERATED by the Base/General tab's "Save design" button --
 * hand edits here get overwritten the next time it's clicked. A full
 * snapshot of every real theme's current Color System (every role's
 * base + all 5 other variants), Alerts, Page leaves, and Custom UI
 * colors' role/stop, captured exactly as they sat at the moment
 * "Save design" was last run. Never contains `label`/`required` --
 * this is a pure VALUE snapshot, never a schema change. See
 * config/theme-designer-colors.php's own `themes` section for the
 * DIFFERENT, hand-edited, rare-schema-override mechanism this merges
 * alongside (both layer onto the site config; this file is always
 * the freshest layer for values). Required by themedesigner/CLAUDE.md's
 * "Config-driven Color System" section. */
return [
    'coastal' => [
        'roles' => [
            'primary' => [
                'default' => '#4c00ff',
                'locked' => [
                    'light' => '#7f7eff',
                    'dark' => '#2c00a4',
                    'medium' => '#4c51b0',
                    'accent' => '#5100ff',
                    'complement' => '#b3ff00',
                ],
            ],
            'secondary' => [
                'default' => '#5cffce',
                'locked' => [
                    'light' => '#95fff0',
                    'dark' => '#00b48a',
                    'medium' => '#acf0d6',
                    'accent' => '#24ffcb',
                    'complement' => '#ff5c8d',
                ],
            ],
            'neutral' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#8a96b8',
                    'dark' => '#141c38',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'dark' => [
                'default' => '#14213d',
                'locked' => [
                    'light' => '#4d5b78',
                    'dark' => '#000005',
                    'medium' => '#1b2230',
                    'accent' => '#122041',
                    'complement' => '#3d3014',
                ],
            ],
            'gray' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#8a96b8',
                    'dark' => '#141c38',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'tertiary' => [
                'default' => '#f7ddb2',
                'locked' => [
                    'light' => '#fffcd5',
                    'dark' => '#ae9772',
                    'medium' => '#ecdfca',
                    'accent' => '#fadcaa',
                    'complement' => '#b2ccf7',
                ],
            ],
            'customcolor' => [
                'default' => '#ff0000',
                'locked' => [
                    'light' => '#ff846e',
                    'dark' => '#a60000',
                    'medium' => '#ca675a',
                    'accent' => '#ff0000',
                    'complement' => '#00ffff',
                ],
            ],
        ],
        'alerts' => [
            'success' => '#00ae2a',
            'warning' => '#f59e0b',
            'error' => '#f56565',
            'info' => '#3b82f6',
        ],
        'page' => [
            'leaves' => [
                'body' => [
                    'default' => '#fffaf0',
                ],
                'body-medium' => [
                    'default' => '#f3e7e1',
                ],
            ],
        ],
        'customUiColors' => [
            'pre-heading' => [
                'role' => 'primary',
                'stop' => 'base',
            ],
        ],
    ],
    'default' => [
        'roles' => [
            'primary' => [
                'default' => '#00aeef',
                'locked' => [
                    'light' => '#84f6ff',
                    'dark' => '#0069a1',
                    'medium' => '#71a9c9',
                    'accent' => '#00affa',
                    'complement' => '#ef4100',
                ],
            ],
            'secondary' => [
                'default' => '#ff6b4a',
                'locked' => [
                    'light' => '#ffba9a',
                    'dark' => '#ab2803',
                    'medium' => '#d48b79',
                    'accent' => '#ff5e36',
                    'complement' => '#4adeff',
                ],
            ],
            'tertiary' => [
                'default' => '#f7ddb2',
                'locked' => [
                    'light' => '#fffcd5',
                    'dark' => '#ae9772',
                    'medium' => '#ecdfca',
                    'accent' => '#fadcaa',
                    'complement' => '#b2ccf7',
                ],
            ],
            'neutral' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#8a96b8',
                    'dark' => '#141c38',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'dark' => [
                'default' => '#14213d',
                'locked' => [
                    'light' => '#4d5b78',
                    'dark' => '#000005',
                    'medium' => '#1b2230',
                    'accent' => '#122041',
                    'complement' => '#3d3014',
                ],
            ],
            'gray' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#b5beff',
                    'dark' => '#2c3246',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
        ],
        'alerts' => [
            'success' => '#00ae2a',
            'warning' => '#f59e0b',
            'error' => '#f56565',
            'info' => '#3b82f6',
        ],
        'page' => [
            'leaves' => [
                'body' => [
                    'default' => '#fffaf0',
                ],
                'body-medium' => [
                    'default' => '#f3e7e1',
                ],
            ],
        ],
        'customUiColors' => [
            'pre-heading' => [
                'role' => 'primary',
                'stop' => 'base',
            ],
        ],
    ],
];
