<?php

/**
 * AUTO-GENERATED by the Base/General tab's "Save design" button --
 * hand edits here get overwritten the next time it's clicked. A full
 * snapshot of every real theme's current Color System (every role's
 * base + all 5 other variants), Alerts, Page leaves, Custom UI
 * colors' role/stop, and its own on-color Light/Dark fallback choice,
 * captured exactly as they sat at the moment "Save design" was last
 * run. Never contains `label`/`required` --
 * this is a pure VALUE snapshot, never a schema change. See
 * config/theme-designer-colors.php's own `themes` section for the
 * DIFFERENT, hand-edited, rare-schema-override mechanism this merges
 * alongside (both layer onto the site config; this file is always
 * the freshest layer for values). Required by themedesigner/CLAUDE.md's
 * "Config-driven Color System" section. */
return [
    'christmas' => [
        'roles' => [
            'primary' => [
                'default' => '#e40a2d',
                'locked' => [
                    'light' => '#ff7d7a',
                    'dark' => '#8e0000',
                    'medium' => '#b55c59',
                    'accent' => '#f10018',
                    'complement' => '#0ae4c1',
                ],
            ],
            'secondary' => [
                'default' => '#165b33',
                'locked' => [
                    'light' => '#619b73',
                    'dark' => '#001f01',
                    'medium' => '#385440',
                    'accent' => '#005d2e',
                    'complement' => '#5b163e',
                ],
            ],
            'tertiary' => [
                'default' => '#1f2766',
                'locked' => [
                    'light' => '#5866a4',
                    'dark' => '#030023',
                    'medium' => '#262d4b',
                    'accent' => '#1e246e',
                    'complement' => '#665e1f',
                ],
            ],
            'neutral' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#8a96b8',
                    'dark' => '#141c38',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'dark' => [
                'default' => '#14213d',
                'locked' => [
                    'light' => '#4d5b78',
                    'dark' => '#000005',
                    'medium' => '#1b2230',
                    'accent' => '#122041',
                    'complement' => '#3d3014',
                ],
            ],
            'gray' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#b5beff',
                    'dark' => '#2c3246',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
        ],
        'alerts' => [
            'success' => '#00ae2a',
            'warning' => '#f59e0b',
            'error' => '#f56565',
            'info' => '#3b82f6',
        ],
        'page' => [
            'leaves' => [
                'body' => [
                    'default' => '#fffaf0',
                ],
                'body-medium' => [
                    'default' => '#f3e7e1',
                ],
                'text-color' => [
                    'default' => '#2c3246',
                ],
            ],
        ],
        'onColorChoices' => [
            'light' => '#ffffff',
            'dark' => '#000000',
        ],
    ],
    'default' => [
        'roles' => [
            'primary' => [
                'default' => '#00aeef',
                'locked' => [
                    'light' => '#84f6ff',
                    'dark' => '#0069a1',
                    'medium' => '#71a9c9',
                    'accent' => '#00affa',
                    'complement' => '#2d9d6f',
                ],
            ],
            'secondary' => [
                'default' => '#ff6b4a',
                'locked' => [
                    'light' => '#ffba9a',
                    'dark' => '#ab2803',
                    'medium' => '#d48b79',
                    'accent' => '#ff5e36',
                    'complement' => '#ffc94d',
                ],
            ],
            'tertiary' => [
                'default' => '#f7ddb2',
                'locked' => [
                    'light' => '#fffcd5',
                    'dark' => '#ae9772',
                    'medium' => '#ecdfca',
                    'accent' => '#fadcaa',
                    'complement' => '#b2ccf7',
                ],
            ],
            'neutral' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#8a96b8',
                    'dark' => '#141c38',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'dark' => [
                'default' => '#14213d',
                'locked' => [
                    'light' => '#4d5b78',
                    'dark' => '#000005',
                    'medium' => '#1b2230',
                    'accent' => '#122041',
                    'complement' => '#3d3014',
                ],
            ],
            'gray' => [
                'default' => '#4a5578',
                'locked' => [
                    'light' => '#b5beff',
                    'dark' => '#2c3246',
                    'medium' => '#505668',
                    'accent' => '#48557d',
                    'complement' => '#786d4a',
                ],
            ],
            'text' => [
                'default' => '#ecdfca',
                'locked' => [
                    'light' => '#ffffff',
                    'dark' => '#111626',
                    'medium' => '#e6e0d5',
                    'accent' => '#eedfc7',
                    'complement' => '#cad7ec',
                ],
            ],
        ],
        'alerts' => [
            'success' => '#00ae2a',
            'warning' => '#f59e0b',
            'error' => '#f56565',
            'info' => '#3b82f6',
        ],
        'page' => [
            'leaves' => [
                'body' => [
                    'default' => '#fffaf0',
                ],
                'body-medium' => [
                    'default' => '#f3e7e1',
                ],
                'text-color' => [
                    'default' => '#111626',
                ],
            ],
        ],
        'onColorChoices' => [
            'light' => '#ffffff',
            'dark' => '#000000',
        ],
    ],
    'scale' => [
        'viewportMin' => 320,
        'viewportMax' => 1440,
        'type' => [
            'minBasePx' => 16,
            'maxBasePx' => 18,
            'ratio' => 1.25,
        ],
        'spacing' => [
            'minBasePx' => 4,
            'maxBasePx' => 6,
            'ratio' => 1.5,
            'pairs' => [
                [
                    'minStep' => 5,
                    'maxStep' => 7,
                ],
                [
                    'minStep' => 8,
                    'maxStep' => 10,
                ],
                [
                    'minStep' => 7,
                    'maxStep' => 9,
                ],
                [
                    'minStep' => 7,
                    'maxStep' => 8,
                ],
                [
                    'minStep' => 4,
                    'maxStep' => 6,
                ],
            ],
        ],
        'weight' => [
            'light' => 300,
            'normal' => 400,
            'medium' => 500,
            'semibold' => 600,
            'bold' => 700,
            'heavy' => 800,
        ],
        'lineHeight' => [
            'impact' => 0.95,
            'tight' => 1.05,
            'normal' => 1.5,
            'loose' => 1.7,
        ],
        'letterSpacing' => [
            'tight' => -0.02,
            'normal' => 0,
            'loose' => 0.04,
            'wide' => 0.08,
        ],
    ],
];
