columnSuffix: null
handle: accordionItem
instructions: null
name: 'Accordion Item'
searchable: false
settings:
  createButtonLabel: 'New item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 7de5631f-7155-48e5-9fdf-aaad1106f353 # Accordion Item
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
