columnSuffix: null
handle: blogCategories
instructions: null
name: 'Blog Categories'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  source: 'group:55fffc15-ee18-4ff7-8465-c6485a3eff57' # Blog Category
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
