columnSuffix: null
handle: columnBuilder
instructions: null
name: 'Column Builder'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  entryTypes:
    -
      uid: 4e8cb0f8-a886-434e-a152-7b57781c7dac # Form
    -
      uid: fbf7c462-6389-4d7d-bc1c-d0b7ff96ccc9 # Blockquote
    -
      uid: 1698acf0-492b-424c-856a-31e8fb8e519f # Buttons
    -
      uid: 6263b46c-0b91-4d57-8b2c-6c07d56c319a # Image
  fullGraphqlData: true
  headingLevels:
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: Default.js
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bookmark
    - sourceEditing
    - '|'
    - createEntry
    - style
    - heading
    - '|'
    - alignment
    - fontColor
    - bulletedList
    - numberedList
    - bold
    - italic
    - underline
    - strikethrough
    - superscript
    - subscript
    - horizontalLine
    - findAndReplace
    - link
    - removeFormat
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
