columnSuffix: null
handle: columnBuilder
instructions: null
name: 'Column Builder'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4e8cb0f8-a886-434e-a152-7b57781c7dac # Form
    -
      __assoc__:
        -
          - uid
          - fbf7c462-6389-4d7d-bc1c-d0b7ff96ccc9 # Blockquote
    -
      __assoc__:
        -
          - uid
          - 1698acf0-492b-424c-856a-31e8fb8e519f # Buttons
    -
      __assoc__:
        -
          - uid
          - 6263b46c-0b91-4d57-8b2c-6c07d56c319a # Image
    -
      __assoc__:
        -
          - uid
          - e5434020-b731-4f0b-b995-c77436af8ad3 # Text
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
