columnSuffix: null
handle: eventUrl
instructions: 'Where people sign up, if that happens somewhere else.'
name: 'Registration URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
