columnSuffix: null
handle: eventLocationName
instructions: 'Where it happens, e.g. “Rincon Vista Sports Center”.'
name: Venue
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
