columnSuffix: null
handle: form
instructions: null
name: Form
searchable: false
settings:
  errorMessage: 'Component class ''verbb\formie\fields\Forms'' belongs to a disabled plugin (Formie).'
  expectedType: verbb\formie\fields\Forms
  settings:
    __assoc__:
      0:
        - allowSelfRelations
        - false
      2:
        - localizeRelations
        - false
      3:
        - maintainHierarchy
        - false
      4:
        - maxRelations
        - 1
      5:
        - minRelations
        - 1
      7:
        - showCardsInGrid
        - false
      8:
        - showSiteMenu
        - true
      9:
        - sources
        - '*'
      11:
        - validateRelatedElements
        - false
      12:
        - viewMode
        - list
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
