columnSuffix: null
handle: iconPicker
instructions: null
name: Icon
searchable: false
settings:
  enableSearch: true
  iconSet: null
  iconSize: medium
  showLabels: false
translationKeyFormat: null
translationMethod: none
type: modules\iconpicker\fields\IconPicker
