columnSuffix: null
handle: intro
instructions: null
name: Intro
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options:
    __assoc__:
      -
        - alignment
        -
          __assoc__:
            -
              - options
              -
                - left
                - center
                - right
      -
        - code
        -
          __assoc__:
            -
              - indentSequence
              - '  '
      -
        - link
        -
          __assoc__:
            -
              - decorators
              -
                __assoc__:
                  -
                    - isExternal
                    -
                      __assoc__:
                        -
                          - attributes
                          -
                            __assoc__:
                              -
                                - rel
                                - 'noopener noreferrer'
                              -
                                - target
                                - _blank
                        -
                          - label
                          - 'Open in new tab'
                        -
                          - mode
                          - manual
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - sourceEditing
    - bold
    - italic
    - superscript
    - subscript
    - link
    - alignment
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
