columnSuffix: null
handle: itemIcon
instructions: null
name: Icon
searchable: false
settings:
  enableSearch: true
  iconSets: '*'
  iconSize: medium
  showLabels: false
translationKeyFormat: null
translationMethod: none
type: modules\iconpicker\fields\IconPicker
