columnSuffix: null
handle: jobSalaryUnit
instructions: 'What the figures above are per.'
name: 'Salary Per'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Year
        -
          - value
          - YEAR
        -
          - default
          - true
    -
      __assoc__:
        -
          - label
          - Month
        -
          - value
          - MONTH
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Week
        -
          - value
          - WEEK
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Day
        -
          - value
          - DAY
        -
          - default
          - false
    -
      __assoc__:
        -
          - label
          - Hour
        -
          - value
          - HOUR
        -
          - default
          - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
