columnSuffix: null
handle: layoutPosts
instructions: null
name: 'Layout Posts'
searchable: false
settings:
  customOptions: false
  displayAsGraphic: true
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Grid
        -
          - showLabel
          - '1'
        -
          - value
          - grid
        -
          - imageUrl
          - /assets/cms/images/layout-posts-grid.svg
        -
          - imageAlign
          - top
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - List
        -
          - showLabel
          - '1'
        -
          - value
          - list
        -
          - imageUrl
          - /assets/cms/images/layout-posts-list.svg
        -
          - imageAlign
          - top
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Slider
        -
          - showLabel
          - '1'
        -
          - value
          - slider
        -
          - imageUrl
          - /assets/cms/images/layout-posts-slider.svg
        -
          - imageAlign
          - top
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
