columnSuffix: null
handle: postBuilder
instructions: null
name: 'Post Builder'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  entryTypes:
    -
      uid: e4ee161b-5e14-4ef6-9d38-81a9062ca4c0 # Cards
    -
      uid: edf679ff-85ed-447c-b175-5652beaf66a5 # Spotlight
    -
      uid: 5623772f-bd7e-44e8-83fd-fd323f950568 # Hero
    -
      uid: 6263b46c-0b91-4d57-8b2c-6c07d56c319a # Image
    -
      uid: 39f2f3de-fe5d-448e-9c6b-914508990b4d # Video
    -
      uid: 1a3dc872-2139-4247-a9aa-a269bf1b80ac # Accordion
    -
      uid: fbf7c462-6389-4d7d-bc1c-d0b7ff96ccc9 # Blockquote
    -
      uid: 1698acf0-492b-424c-856a-31e8fb8e519f # Buttons
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: Default.js
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bookmark
    - sourceEditing
    - '|'
    - createEntry
    - style
    - heading
    - '|'
    - alignment
    - fontColor
    - bulletedList
    - numberedList
    - bold
    - italic
    - underline
    - strikethrough
    - superscript
    - subscript
    - horizontalLine
    - findAndReplace
    - link
    - removeFormat
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
