columnSuffix: null
handle: subheading
instructions: null
name: Subheading
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
    - 4
    - 5
    - 6
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: Heading.json
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - bold
    - italic
    - superscript
    - subscript
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
