columnSuffix: null
handle: tickerDirection
instructions: 'Which way the row moves.'
name: 'Ticker Direction'
searchable: false
settings:
  customOptions: false
  displayAsGraphic: false
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - showLabel
          - '1'
        -
          - value
          - left
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - showLabel
          - '1'
        -
          - value
          - right
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
