columnSuffix: null
handle: youtubeUrl
instructions: null
name: 'YouTube URL'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
