dateModified: 1784397576
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      page: Entries
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:b78072c7-6221-4c3b-abce-421951b79f79' # Pages
      page: Entries
      type: native
    -
      heading: Posts
      key: 'heading:54307306-d1d7-4669-a8f9-f7c98c7b6a04'
      page: Entries
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:31880924-79a0-4c1f-abad-f9a3baf7286b' # Books
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:dd38050d-50f7-44c7-adcc-b1c8a01d01a3' # Blog
      page: Entries
      type: native
    -
      heading: ''
      key: 'heading:12fe1838-ce08-4b42-8d72-fe8722b2de12'
      page: Entries
      type: heading
email:
  fromEmail: gary@ramzcreative.com
  fromName: $SITE_NAME
  replyToEmail: info@ramzcreative.com
  template: null
  transportSettings:
    host: $EMAIL_HOST
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    useAuthentication: '1'
    username: $EMAIL_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      bucket: $DIGITAL_BUCKET
      contentDisposition: ''
      endpoint: $DIGITAL_ENDPOINT
      expires: '3 months'
      keyId: $DIGITAL_KEY_ID
      region: $DIGITAL_REGION
      secret: $DIGITAL_KEY_SECRET
      subfolder: files
    type: vaersaagod\dospaces\Fs
    url: $DIGITAL_CDN
  images:
    hasUrls: true
    name: Images
    settings:
      bucket: $DIGITAL_BUCKET
      contentDisposition: ''
      endpoint: $DIGITAL_ENDPOINT
      expires: '25 days'
      keyId: $DIGITAL_KEY_ID
      region: $DIGITAL_REGION
      secret: $DIGITAL_KEY_SECRET
      subfolder: images
    type: vaersaagod\dospaces\Fs
    url: $DIGITAL_CDN
  videos:
    hasUrls: false
    name: Videos
    settings:
      bucket: $DIGITAL_BUCKET
      contentDisposition: ''
      endpoint: $DIGITAL_ENDPOINT
      expires: '3 months'
      keyId: $DIGITAL_KEY_ID
      region: $DIGITAL_REGION
      secret: $DIGITAL_KEY_SECRET
      subfolder: videos
    type: vaersaagod\dospaces\Fs
    url: null
meta:
  __names__:
    1a3dc872-2139-4247-a9aa-a269bf1b80ac: Accordion # Accordion
    1be88a3f-f16d-4b16-a3b6-94929ea072bd: Images # Images
    1df3f4cc-b5a3-459f-8307-e057851474cc: Content # Content
    1e94c6e9-319f-45cf-8383-63e71bc5728f: 'Circle Images' # Circle Images
    2b6560e1-50b4-4e56-a7b1-a380918d0346: 'Entry Heading' # Entry Heading
    2c71aa3d-133a-4b8c-9db4-94f0afaf981d: Bookmark # Bookmark
    3d118907-1a93-4a51-850b-17bb343d1c28: 'Intro Text' # Intro Text
    4bff64c9-1917-4608-af7d-2ad9e3197306: Posts # Posts
    4ca162dc-c397-4e46-9c1d-64ad71e33e02: 'Word Search Words' # Word Search Words
    4d0fc2f7-2cbb-42fa-8fd9-4a41385243db: Active # Active
    4d4ed4f3-190b-4e97-a563-3eff29c7f476: Banner # Banner
    4e8cb0f8-a886-434e-a152-7b57781c7dac: Form # Form
    5b4f3d2f-8a5f-4c3f-bc49-1010ee7cb808: Entries # Entries
    5df22e15-45f0-4766-8d0a-4d95df967f40: 'Background Image' # Background Image
    06a034b6-5551-4f15-bd0a-2276abce862e: 'Romeo & Buddy' # Romeo & Buddy
    6ae4668b-587f-4a92-a101-f11e6fbeb416: 'Cite Name' # Cite Name
    6b4778ab-9b3c-49f1-a836-0f7a8c2d70c4: 'Text Plain' # Text Plain
    7c30c73f-7393-4bfc-b722-7cdeef05d98d: 'Maze Difficulty' # Maze Difficulty
    7de5631f-7155-48e5-9fdf-aaad1106f353: 'Accordion Item' # Accordion Item
    7eba1a3e-38a0-4731-accf-66ecb6e2db5e: 'Activity Type' # Activity Type
    08b48d59-4ae5-4abf-b1db-53196d409a85: 'Layout Button' # Layout Button
    9cf20a01-5f94-41d0-9696-def07b1170c6: Item # Item
    9e868b65-f793-417d-856c-90539337418d: Reverse # Reverse
    9fe35334-f235-4cbd-830d-20551ed7f0de: Items # Items
    25cfa505-377c-4b52-b184-520953fa87b9: 'Image Items' # Image Items
    28e6f572-c5de-4726-85ef-7676117576ff: Excerpt # Excerpt
    30af8605-1ce8-4624-b1e1-a329ec2264a1: Offset # Offset
    39f2f3de-fe5d-448e-9c6b-914508990b4d: Video # Video
    46e860b1-f2f5-4ab7-ad6c-8a06ce366313: 'Contact Form' # Contact Form
    48fcd1e6-b9a6-42c3-beb4-963c7c0afa5c: Intro # Intro
    55fffc15-ee18-4ff7-8465-c6485a3eff57: 'Blog Category' # Blog Category
    66e80c55-74d5-43db-9559-0c264675c2b1: 'Icon Cards' # Icon Cards
    68e5ca04-1054-4e55-aabd-aaab0bb906b9: Form # Form
    70ac0c99-61b2-431e-be95-bb8c7c932f5d: Genre # Genre
    71e40ac8-9d14-4c1b-8a8d-4c7394b44726: 'Age Range' # Age Range
    085eb676-ba17-4724-8ba0-ae70571428ff: Buttons # Buttons
    96b92e53-6e30-4829-a045-983163aff055: 'Image + Text' # Image + Text
    108ef096-30ee-4adf-a31e-51f1591e568f: 'Link Url' # Link Url
    194a1d77-1959-415c-ba8a-29f4f519d6d4: 'Layout Image Text' # Layout Image Text
    497ae096-5be1-4540-8bf6-e27c403ce8e7: Email # Email
    518cac2e-e652-4731-b2af-e2e73d5f75e4: Subheading # Subheading
    724aadcc-b44a-43c5-90c9-7b4bb9249b0f: 'Typewriter Phrases' # Typewriter Phrases
    741fd71d-6888-41e2-9711-3304d957e9f2: 'Accordion Item' # Accordion Item
    761cb901-155c-4af8-b4ae-2838334c31c1: SEO # SEO
    1698acf0-492b-424c-856a-31e8fb8e519f: Buttons # Buttons
    3881f2a7-06d2-4516-9453-9996e3d07058: 'Blog Categories' # Blog Categories
    4235f2db-a69d-4ee4-bb4f-bffb8c69fc46: Alignment # Alignment
    6195ab36-3dd4-4829-9521-4c0113e3438e: Format # Format
    6244faa5-03d1-48be-81b8-ccb54c5ac3f4: Icon # Icon
    6263b46c-0b91-4d57-8b2c-6c07d56c319a: Image # Image
    8133dc93-b000-4c07-86a6-922163474816: 'Coming Soon' # Coming Soon
    8941db8e-efce-4915-bf8f-69eb0f8a5278: Header # Header
    60485a27-304f-4d3f-bb6e-3a989e1304d3: 'Cite Title' # Cite Title
    71600c0c-f823-486e-a052-511b73c99e42: 'Layout Columns' # Layout Columns
    87746e2a-c7bc-4b6e-a78f-6e4e1a02830f: Files # Files
    456164d2-7d55-484c-8c85-e5c3c811c7e7: Slider # Slider
    530722fb-a5ad-4da8-8125-258d68d2d5f8: Book # Book
    678106cb-b48e-4351-a5db-2c4d8a9cf60c: Author # Author
    850076b3-fd0a-414f-8146-42950f83426b: Autoplay # Autoplay
    5623772f-bd7e-44e8-83fd-fd323f950568: Hero # Hero
    7905031c-3482-4874-ae43-5aed9de263d0: 'Page Builder' # Page Builder
    31880924-79a0-4c1f-abad-f9a3baf7286b: Books # Books
    94274183-5671-4539-bfd0-df73e7b22ada: Page # Page
    a08cfcda-2163-413b-b905-28a09bccf5b9: Button # Button
    a9d5de07-d076-4b02-b115-0f37735d4c31: 'Pre Heading' # Pre Heading
    a52fc47f-27d0-4193-abac-5d57ce6873f3: 'Series Name' # Series Name
    a864f587-7735-4034-ae41-263769dc4757: Heading # Heading
    aa4c0467-92b4-4c41-8752-a8b20f6ddd8c: 'Image Item' # Image Item
    ab74eae5-e2c1-4646-8cad-ffa2eabc8536: 'Post Builder' # Post Builder
    acd689f8-2c89-4283-907d-9c3aefec55cb: Address # Address
    af33ad6a-671e-404f-b7c5-6ec2383aa0e7: Columns # Columns
    b0c47f83-658c-4d6c-a6e2-9fb8ad5f6d92: Column # Column
    b0308dcc-2ed8-4232-9cfd-b38c9d1c0e05: Columns # Columns
    b14ede2e-0faf-4bdb-bb57-7138ac782459: 'Activity Sheet' # Activity Sheet
    b321eb14-711f-4200-8425-1d4c0c7da1b8: 'Column Builder' # Column Builder
    b78072c7-6221-4c3b-abce-421951b79f79: Pages # Pages
    bc73ca95-f2b3-4193-bc1c-1467ea1f745c: Phone # Phone
    bc612dac-df7b-4e99-ba8a-ffa5fa822784: 'Layout Posts' # Layout Posts
    bf1b9609-7719-4507-b83a-8ba5bb3a1665: DoFollow # DoFollow
    c6a97d1c-32c5-4657-8fda-e30af482517d: Video # Video
    c6b67b6f-24c0-49dc-afa2-cb269487d4b7: 'Where to Buy' # Where to Buy
    c9e6e935-5710-4a87-a442-1351e587d602: 'Block Heading' # Block Heading
    c404a85a-ec68-4124-a506-ec72ac1d0cb2: Fullwidth # Fullwidth
    c495e62d-2b26-45c1-963b-89b675217792: 'Post Type' # Post Type
    c68573ad-e194-4c2b-a336-4a3f0681dcdd: 'Layout Cards' # Layout Cards
    cbb5eea4-b59a-4928-a281-00f573c5bb80: General # General
    cc07c179-e1f6-435a-b2e4-0955e3386fc3: Image # Image
    cc56d7d2-b446-40ee-bd3d-7b8e4286b285: 'Blog Back Link' # Blog Back Link
    ccf68957-a957-483a-a712-329de9473ab6: Copyright # Copyright
    cda2ad7b-390d-4efe-bd62-2bd4c517a0d7: 'Contact Form' # Contact Form
    ce58647c-0f14-400b-877c-2d003d0799d6: Footer # Footer
    d3eba5d7-eac7-41a7-98f5-6c13f73fd73d: ISBN # ISBN
    d68614f9-691c-485a-84c0-199f2b91ec8c: 'Blog Post' # Blog Post
    d70298f4-c945-487f-bbd1-daa941825c8e: Header # Header
    dc2969c0-04e5-4147-b890-de60a8d6cda6: 'Block Heading' # Block Heading
    dd2caccc-8448-4e42-91b0-d0915f2caa3d: Column # Column
    dd38050d-50f7-44c7-adcc-b1c8a01d01a3: Blog # Blog
    e3df2aa1-e470-44f2-8fb2-0b8b94d4aed5: Videos # Videos
    e4ee161b-5e14-4ef6-9d38-81a9062ca4c0: Cards # Cards
    e489c49d-c32a-4a51-9e1b-5d0e6d78dd8d: 'Number of Pages' # Number of Pages
    e150044d-b12f-434c-a9f9-d244e2614c38: Illustrator # Illustrator
    e931454e-e978-4832-8fc4-4443cd5e3a99: Primary # Primary
    ed8a955a-d49a-455f-894c-c4e1422fa6ff: Item # Item
    edf679ff-85ed-447c-b175-5652beaf66a5: Spotlight # Spotlight
    edfb9ae5-f698-432c-b828-002685d324fb: Background # Background
    f05974eb-1438-43a1-8a0e-4f5e84183e83: 'Layout Sliders' # Layout Sliders
    f8fafcf7-7710-43f7-ac3d-849407a2dcbe: Width # Width
    f39bd8d3-3114-4beb-9c81-9471d52256a2: 'Public Schema' # Public Schema
    f19378b7-f590-4de3-a89e-aff501dbdf3b: 'Series Position' # Series Position
    f1015394-4ed8-4389-aeb7-b9995c00b13c: New # New
    fbf7c462-6389-4d7d-bc1c-d0b7ff96ccc9: Blockquote # Blockquote
    ffd1c25d-00c2-4f33-bf7f-2986a4d32115: Text # Text
plugins:
  buttonbox:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.6.0.0
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: false
    licenseKey: 62RLTGJEXC8ZQOKT3M24XC0V
    schemaVersion: 3.4.12
  free-nav:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      activeClass: active
      ariaEnabled: true
      cacheDuration: 3600
      cacheEnabled: true
      defaultPreset: sidebar
      hasChildrenClass: has-children
      restApiEnabled: true
  prefetch:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Primary
  schemaVersion: 5.10.0.0
  timeZone: America/Los_Angeles
