defaultPlacement: end
handle: header
instructions: ''
maxLevels: 2
maxNodes: 5
name: Header
propagationMethod: all
sites:
  06a034b6-5551-4f15-bd0a-2276abce862e: # Romeo & Buddy
    enabled: true
structure:
  maxLevels: 2
  uid: 248d2a73-1a0f-4faa-80f1-574c1c11f186
