defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 83710c68-7a3c-4dbf-b41e-86aad6b2a0e7 # Job
handle: jobs
maxAuthors: 1
minAuthors: 1
name: Jobs
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  06a034b6-5551-4f15-bd0a-2276abce862e: # Romeo & Buddy
    enabledByDefault: true
    hasUrls: true
    template: _router.twig
    uriFormat: 'jobs/{slug}'
type: channel
