defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 94274183-5671-4539-bfd0-df73e7b22ada # Page
handle: pages
maxAuthors: 1
minAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  06a034b6-5551-4f15-bd0a-2276abce862e: # Romeo & Buddy
    enabledByDefault: true
    hasUrls: true
    template: _router.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: 08a2cfa4-1948-4865-bfbd-a14970bc7eea
type: structure
